### PR TITLE
Fix type inference for structs

### LINKED ISSUE #143: Tests type inference Ternary and new
See #133
`uint b = a?1:0;` Should be ok for ternary

    uint a = 0;
    new Cls(a+0)

Should be ok for new

### PR DESCRIPTION
**Pull request by machulen**
Closes #143

### CODE REVIEW

File: src/type_inference/stage1.coffee [hunk 1]
```diff
@@ -200,7 +200,11 @@ type_generalize = require "../type_generalize"
     
     when "Var_decl"
       if root.assign_value
-        root.assign_value.type = ti.type_spread_left root.assign_value.type, root.type, ctx
+        if root.assign_value.val_list
```
Comment (vird) [inline src/type_inference/stage1.coffee]: It's better to check type first with .constructor.name == "Struct_init", not to check specific field presense
